### ISSUE TITLE
Generating pseudo label is really time-consuming?

### ISSUE THREAD

**Issue by jiangzhengkai** [BIT-DA/SDCA#2]
Hi, I notice generating pseudo labels is really time-consuming? At the same time, the scale for the pseudo label is (1024, 2048) rather than (512, 1024) for the test process.

**Comment by BinhuiXie** [comment]
Hi, thank you for your comments!
As stated in the paper,  self-supervised learning has been used in previous methods such as [Tsai et al. 2019](https://arxiv.org/pdf/1901.05427.pdf), [Pan et al. 2020](https://arxiv.org/pdf/2004.07703v4.pdf), [Wang et al. 2020](https://arxiv.org/pdf/2007.09222.pdf) and so on, which is usually achieved by iteratively generating a set of pseudo labels based on the most confident predictions on the target data. Our contrastive adaptation strategy is over the feature representations and is orthogonal to the self-supervised learning. Here, we utilize a large resolution because we find it does help increase our performance.
